### ISSUE TITLE
Bug: утилита аварийно завершается при анализе c/cpp файлов с не латинскими строками  

### ISSUE THREAD

**Issue by mirrin00** [OSLL/code-plagiarism#166]
## Описание
Парсинг features для файлов падает, если в коде присутствует не латинская строка

## Код для воспроизведения
```c
#include <stdio.h>

int main()
{
    printf("Äàííûå íåêîððåêòíû\n");
    return 0;
}
```
"Побитая" строка -- это "Данные некорректны" (на GitHub код залит прямо в таком виде, искажение при скачивании исключено)

## Ожидаемое поведение
* Предпочтительный вариант: файл будет проанализирован без ошибок
  * Автоподбор формата декодирования?
  * Игнорирование части, в которой происходит ошибка
* Другой вариант: предупреждение о том, что файл "странный" и утилита не может его проверить
  * Генерация дополнительного отчёта с файлами, которые не удалось проверить

## Получаемый результат
```
[ERROR] 08:21 - An unexpected error occurred while running the utility. For getting more information, check file '/var/log/codeplag/codeplag.log'.
$ cat /var/log/codeplag/codeplag.log
Jul 10 08:21:24 - [DEBUG] - codeplag - (utils.py).run(368) - Starting codeplag util
Jul 10 08:21:34 - [WARNING] - codeplag - (getfeatures.py)._set_access_token(80) - Env file not found or not a file. Trying to get token from environment.
Jul 10 08:21:34 - [WARNING] - codeplag - (getfeatures.py)._set_access_token(90) - GitHub access token is not defined.
Jul 10 08:21:34 - [DEBUG] - codeplag - (utils.py).run(368) - Starting codeplag util
Jul 10 08:21:34 - [DEBUG] - codeplag - (utils.py)._check(270) - Mode: many_to_many; Extension: cpp.
Jul 10 08:21:34 - [INFO] - codeplag - (utils.py)._check(282) - Starting searching for plagiarism
Jul 10 08:21:34 - [INFO] - codeplag - (getfeatures.py).get_from_dirs(131) - Getting works features from /usr/src/volume
Jul 10 08:21:35 - [ERROR] - codeplag - (__init__.py).main(28) - An unexpected error occurred while running the utility. For getting more information, check file '/var/log/codeplag/codeplag.log'.
Jul 10 08:21:35 - [DEBUG] - codeplag - (__init__.py).main(32) - Trace:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/codeplag/__init__.py", line 23, in main
    codeplag_util.run()
  File "/usr/local/lib/python3.8/dist-packages/codeplag/utils.py", line 379, in run
    self._check()
  File "/usr/local/lib/python3.8/dist-packages/codeplag/utils.py", line 287, in _check
    self.features_getter.get_from_dirs(
  File "/usr/local/lib/python3.8/dist-packages/codeplag/getfeatures.py", line 132, in get_from_dirs
    new_works = self.get_works_from_dir(directory)
  File "/usr/local/lib/python3.8/dist-packages/codeplag/cplag/utils.py", line 104, in get_works_from_dir
    return get_works_from_filepaths(filepaths, COMPILE_ARGS)
  File "/usr/local/lib/python3.8/dist-packages/codeplag/cplag/utils.py", line 48, in get_works_from_filepaths
    features = get_features(cursor, filepath)
  File "/usr/local/lib/python3.8/dist-packages/codeplag/cplag/tree.py", line 83, in get_features
    features.literals[token.spelling] += 1
  File "/usr/local/lib/python3.8/dist-packages/clang/cindex.py", line 3386, in spelling
    return conf.lib.clang_getTokenSpelling(self._tu, self)
  File "/usr/local/lib/python3.8/dist-packages/clang/cindex.py", line 229, in from_result
    return conf.lib.clang_getCString(res)
  File "/usr/local/lib/python3.8/dist-packages/clang/cindex.py", line 104, in to_python_string
    return x.value
  File "/usr/local/lib/python3.8/dist-packages/clang/cindex.py", line 89, in value
    return super(c_char_p, self).value.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1: invalid continuation byte
```

**Comment by Artanias** [comment]
> Как (и насколько сильно) влияют строковые литералы на точность поиска плагиата?

Это не должно повлиять ни на что за исключением того, что просто строка немного будет преобразована, например, для случая выше в:

```
#include <stdio.h>

int main()
{
    printf("\n");
    return 0;
}
```

А в результате будет преобразовано к одному и тому же дереву/токенам.

Но это изменение будет только во внутреннем представлении.

**Comment by mirrin00** [comment]
> А в результате будет преобразовано к одному и тому же дереву/токенам.

Хорошо, тогда согласен, можно игнорировать такие части
