### ISSUE TITLE
Падает проверка на одной из форм регулярного выражения, проверить почему.

### ISSUE THREAD

**Issue by Artanias** [OSLL/code-plagiarism#56]

**Comment by Artanias** [comment]
`$ python3 -m codeplag.pyplag -g OSLL -e "sm" -f ./src/codeplag/pyplag/utils.py

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/user/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/user/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/user/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/user/.local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/user/.local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd7fb161310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/user/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/user/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/OSLL/ns3psm/git/trees/3e8b9ed66d873b6c483765d008d118527265c069 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd7fb161310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/lib/python3.8/site-packages/codeplag-0.0.1-py3.8.egg/codeplag/pyplag/__main__.py", line 55, in <module>
    for file, url_file in files:
  File "/home/user/.local/lib/python3.8/site-packages/codeplag-0.0.1-py3.8.egg/webparsers/github_parser.py", line 204, in get_files_generator_from_repo_url
    yield from self.get_files_generator_from_sha_commit(
  File "/home/user/.local/lib/python3.8/site-packages/codeplag-0.0.1-py3.8.egg/webparsers/github_parser.py", line 146, in get_files_generator_from_sha_commit
    yield from self.get_files_generator_from_sha_commit(
  File "/home/user/.local/lib/python3.8/site-packages/codeplag-0.0.1-py3.8.egg/webparsers/github_parser.py", line 146, in get_files_generator_from_sha_commit
    yield from self.get_files_generator_from_sha_commit(
  File "/home/user/.local/lib/python3.8/site-packages/codeplag-0.0.1-py3.8.egg/webparsers/github_parser.py", line 146, in get_files_generator_from_sha_commit
    yield from self.get_files_generator_from_sha_commit(
  [Previous line repeated 1 more time]
  File "/home/user/.local/lib/python3.8/site-packages/codeplag-0.0.1-py3.8.egg/webparsers/github_parser.py", line 141, in get_files_generator_from_sha_commit
    response_json = self.send_get_request(api_url).json()
  File "/home/user/.local/lib/python3.8/site-packages/codeplag-0.0.1-py3.8.egg/webparsers/github_parser.py", line 63, in send_get_request
    response = requests.get(address + api_url, headers=headers,
  File "/home/user/.local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/OSLL/ns3psm/git/trees/3e8b9ed66d873b6c483765d008d118527265c069 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd7fb161310>: Failed to establish a new connecti
`

**Comment by Artanias** [comment]
Если проверять чисто данный репозиторий, то проверка завершается успешно, попробовать ещё раз, может интернет соединение оборвалось.
