### ISSUE TITLE
Корректно обрабатывать логером ошибки некорректной ссылки в webparsers.

### ISSUE THREAD

**Issue by Artanias** [OSLL/code-plagiarism#90]

**Comment by Artanias** [comment]
Основная проблема на данный момент, что выводится весь tracebake в консоль при возникновении ошибки:
`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/artaband/.local/lib/python3.8/site-packages/codeplag/__main__.py", line 76, in <module>
    tree = get_ast_from_content_py(gh.get_file_from_url(github_file)[0],
  File "/home/artaband/.local/lib/python3.8/site-packages/webparsers/github_parser.py", line 247, in get_file_from_url
    owner, repo, branch, path = self.parse_content_url(file_url)
  File "/home/artaband/.local/lib/python3.8/site-packages/webparsers/github_parser.py", line 49, in parse_content_url
    raise ValueError('Incorrect link to content of GitHub repository')
ValueError: Incorrect link to content of GitHub repository
`
